[build]
  publish = "."
[functions]
  directory = "netlify/functions"
[[redirects]]
  from = "/webhook/telegram"
  to = "/.netlify/functions/telegram-bot"
  status = 200
[[redirects]]
  from = "/webhook/respond-io"
  to = "/.netlify/functions/respond-io-webhook"
  status = 200
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"